remote_theme: APIDevTools/gh-pages-theme

title: JSON Schema $Ref Parser
logo: /img/logos/logo.png

author:
  twitter: APIDevTools

google_analytics: UA-68102273-2

twitter:
  username: APIDevTools
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: /img/logos/card.png
