remote_theme: APIDevTools/gh-pages-theme

title: JSON Schema $Ref Parser
logo: http://apidevtools.org/img/logos/logo.png

author:
  twitter: APIDevTools

google_analytics: UA-68102273-2

twitter:
  username: APIDevTools
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: http://apidevtools.org/img/logos/card.png
  - scope:
      path: "test/specs/**/*"
    values:
      sitemap: false

plugins:
  - jekyll-sitemap
